// export const MODE_TYPE_UPDATE = 'MODE_TYPE_UPDATE';
// export const MODE_IMPORT_MODAL_UPDATE = 'MODE_IMPORT_MODAL_UPDATE';

export const API_GET = 'API_GET';
export const JSON_DATA_UPDATE = 'JSON_DATA_UPDATE';
export const JSON_DATA_TEMP_ADD = 'JSON_DATA_TEMP_ADD';
export const JSON_DATA_TEMP_REMOVE = 'JSON_DATA_TEMP_REMOVE';
export const JSON_DATA_EDIT_TEMP_ADD = 'JSON_DATA_EDIT_TEMP_ADD';
export const JSON_DATA_EDIT_TEMP_REMOVE = 'JSON_DATA_EDIT_TEMP_REMOVE';

export const SCOPE_FLAGS_UPDATE = 'SCOPE_FLAGS_UPDATE';
export const SCOPE_FLAGS_REMOVE = 'SCOPE_FLAGS_REMOVE';

export const SCOPE_DATA_TEXTAREA_UPDATE = 'SCOPE_DATA_TEXTAREA_UPDATE';

export const SCOPE_SEND_TYPE_UPDATE = 'SCOPE_SEND_TYPE_UPDATE';
export const SCOPE_SEND_API_TYPE = 'SCOPE_SEND_API_TYPE';
