export const JSON_DATA_GET = 'JSON_DATA_GET';
export const JSON_DATA_UPDATE = 'JSON_DATA_UPDATE';

export const SCOPE_FLAGS_UPDATE = 'SCOPE_FLAGS_UPDATE';
export const SCOPE_FLAGS_REMOVE = 'SCOPE_FLAGS_REMOVE';

export const SCOPE_DATA_TEXTAREA_UPDATE = 'SCOPE_DATA_TEXTAREA_UPDATE';

export const SCOPE_SEND_TYPE_UPDATE = 'SCOPE_SEND_TYPE_UPDATE';
