export const CRUD_URL_UPDATE = 'CRUD_URL_UPDATE';
export const CRUD_TYPE_UPDATE = 'CRUD_TYPE_UPDATE';
export const CRUD_DATA_UPDATE = 'CRUD_DATA_UPDATE';
export const CRUD_RESPONSE_UPDATE = 'CRUD_RESPONSE_UPDATE';
